#!/bin/bash

figlet "pachhh" | lolcat
echo ""
echo -e "Thanks for using autonmap! Designed for TryHackMe, HackTheBox and labs." | lolcat
echo ""

# Colors
RED="\033[31m"
GREEN="\033[32m"
BLUE="\033[34m"
RESET="\033[0m"

# Argument check
TARGET=$1

if [ "$#" -lt 1 ]; then
  echo -e "${RED}[!] Usage: $0 <IP or domain>${RESET}"
  exit 1
fi

# Resolve IP if domain is given
if [[ "$TARGET" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  IP="$TARGET"
else
  IP=$(dig +short "$TARGET" | head -n1)
  if [ -z "$IP" ]; then
    echo -e "${RED}[!] Could not resolve domain: ${BLUE}$TARGET${RESET}"
    exit 1
  fi
  echo -e "${GREEN}[*] Domain resolved to IP: ${BLUE}$IP${RESET}"
fi

# Create folder and scan files
mkdir -p "$IP"
SCAN_FILE="$IP/scan_$(date +%F_%H-%M).txt"
TMPSCAN=$(mktemp)

trap "rm -f $TMPSCAN" EXIT

echo -e "${GREEN}[*] Starting full TCP scan on: ${BLUE} $IP...${RESET}"
nmap -sS -T4 --min-rate 5000 -p- --open -O "$IP" >> "$TMPSCAN"
echo -e "${GREEN}[*] Starting top 100 UDP scan...${RESET}"
nmap -sU --top-ports 100 "$IP" >> "$TMPSCAN"

if [ -s "$TMPSCAN" ]; then
  PORTS=$(grep -oP '^\d+(?=/tcp)' "$TMPSCAN" | tr '\n' ',' | sed 's/,$//')
  echo -e "${GREEN}[*] Open TCP ports: ${BLUE}$PORTS${RESET}"
  echo "Open ports $PORTS" >> "$SCAN_FILE"
  
  echo -e "${GREEN}[*] Running version detection...${RESET}"
  nmap -sV -sC -Pn -p"$PORTS" "$IP" >> "$SCAN_FILE"

  echo -e "${GREEN}[*] Starting web enumeration...${RESET}"
  PORT_LIST=$(echo "$PORTS" | tr ',' ' ')
  
  for p in $PORT_LIST; do
    LINE=$(grep "$p/tcp" "$TMPSCAN" | awk '{print tolower($3)}')
    if [[ "$LINE" == *"https"* || "$LINE" == *"ssl"* ]]; then
        URL="https://$IP:$p"
      else
        URL="http://$IP:$p"
    fi
      echo -e "${GREEN}[*] Gobuster on: ${BLUE} $URL${RESET}"
      echo -e "\n[+] Gobuster on: ${BLUE} $URL" >> "$SCAN_FILE"
      gobuster dir -u "$URL" -w "/home/pachhh/tool/SecLists/Discovery/Web-Content/directory-list-2.3-medium.txt" >> "$SCAN_FILE" 2>&1
  done
else
  echo -e "${RED}[!] No data collected from scans${RESET}"
fi

echo -e "${GREEN}[*] Scan complete. Output saved in: ${BLUE} ${SCAN_FILE}${RESET}"
